[project]
name = "fastmeteo"
version = "1.0.0"
description = "Fast interpolation for ERA5 data with Zarr"
authors = [{ name = "Junzi Sun", email = "j.sun-1@tudelft.nl" }]
license = { text = "GNU LGPL v3" }
readme = "readme.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.8",
    "dask>=2025.3.0",
    "fastapi>=0.115.12",
    "fsspec>=2025.3.2",
    "gcsfs>=2025.3.2",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "scipy>=1.15.2",
    "uvicorn>=0.34.1",
    "xarray>=2025.3.1",
    "zarr (>=2.18.2,<3.0.0)",
]


[project.urls]
homepage = "https://github.com/open-aviation/fastmeteo"
repository = "https://github.com/open-aviation/fastmeteo"
issues = "https://github.com/open-aviation/fastmeteo/issues"

[tool.uv]
dev-dependencies = ["ipykernel>=6.29.5", "ruff>=0.11.5", "mypy>=1.15.0"]

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
select = [
    "E",
    "W",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "NPY", # numpy
    # "PD",  # pandas
    "DTZ", # flake8-datetimez
    "RUF",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
